In [1]:
import torch
import numpy as np

In [5]:
a =np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [6]:
b =torch.from_numpy(a)

In [7]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [8]:
a += 1

In [9]:
print(a)

[2. 2. 2. 2. 2.]


In [10]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [15]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  x = torch.ones(5,device= device)
  y =torch.ones(5)
  y =y.to(device)
  z = x + y
  z = z.to('cpu')

In [16]:
x = torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
